CREATE TABLE IF NOT EXISTS projects(
 id uuid PRIMARY KEY,name text NOT NULL,file_name text NOT NULL,stored_name text NOT NULL UNIQUE,file_size bigint NOT NULL,status text NOT NULL DEFAULT 'uploaded',progress smallint NOT NULL DEFAULT 0,findings_count integer NOT NULL DEFAULT 0,error_message text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS projects_created_idx ON projects(created_at DESC);
CREATE TABLE IF NOT EXISTS jobs(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,type text NOT NULL,status text NOT NULL DEFAULT 'queued',attempts integer NOT NULL DEFAULT 0,error_message text,started_at timestamptz,finished_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS jobs_project_idx ON jobs(project_id,created_at DESC);
CREATE TABLE IF NOT EXISTS documents(id bigserial PRIMARY KEY,project_id uuid NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,format text NOT NULL,page_count integer,character_count integer NOT NULL DEFAULT 0,blocks jsonb NOT NULL DEFAULT '[]'::jsonb,parser_version text NOT NULL,parsed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS requirements(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,type text NOT NULL,title text NOT NULL,normalized_value text NOT NULL,mandatory boolean NOT NULL DEFAULT false,evidence jsonb NOT NULL DEFAULT '[]'::jsonb,review_status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS requirements_project_idx ON requirements(project_id,review_status,created_at);
CREATE TABLE IF NOT EXISTS ai_runs(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,job_id uuid REFERENCES jobs(id) ON DELETE SET NULL,chunk_number integer NOT NULL,model text NOT NULL,status text NOT NULL,input_tokens integer NOT NULL DEFAULT 0,output_tokens integer NOT NULL DEFAULT 0,cost_usd numeric(16,10) NOT NULL DEFAULT 0,duration_ms integer,retries integer NOT NULL DEFAULT 0,error_message text,created_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz);
CREATE INDEX IF NOT EXISTS ai_runs_project_idx ON ai_runs(project_id,created_at DESC);